In [1]:
import numpy as np

In [3]:
#1 crear 3 arrays
#unidimensional
lista1 = [7,2,4,3]
array1 = np.array(lista1)
array1

array([7, 2, 4, 3])

In [4]:
#bidimensional
array2 = np.random.randint(0,50, (2,3))
array2

array([[10, 24,  0],
       [28, 24,  0]])

In [5]:
#multidimensional
array3 = np.random.randint(0,50, (2,3,5))
array3

array([[[18, 42, 25,  4,  1],
        [29, 48,  3, 22, 39],
        [32, 11, 18,  4, 11]],

       [[33, 44,  4, 25, 29],
        [13, 35, 22, 17, 42],
        [44, 37, 33, 11, 44]]])

In [9]:
#2 propiedades básicas en una función
def propiedades():
    lista_arrays = [array1, array2, array3]
    for propiedad in lista_arrays:
        print('Este es el tamaño del array',  propiedad.size)
        print('Esta es la dimensión del array', propiedad.ndim)
        print('Este es el tipo de array',  propiedad.dtype)
        print('Esta es la forma del array',  propiedad.shape)
        
propiedades()

Este es el tamaño del array 4
Esta es la dimensión del array 1
Este es el tipo de array int64
Esta es la forma del array (4,)
Este es el tamaño del array 6
Esta es la dimensión del array 2
Este es el tipo de array int64
Esta es la forma del array (2, 3)
Este es el tamaño del array 30
Esta es la dimensión del array 3
Este es el tipo de array int64
Esta es la forma del array (2, 3, 5)


In [11]:
#3 matriz identidad de 3 filas x 3 columnas
array4 = np.eye(3,3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#4 matriz de tres dimensiones de 1 = matriz de 3 dimensiones del 1er ejercicio
array5 = np.ones_like(array3)
array5

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [12]:
#5 operaciones
suma = array4 + array2
print(suma)
#No se puede sumar porque no tienen el mismo nº de filas

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [13]:
# suma 2
array6 = np.eye(3,3)
suma = array6 + array4
print('Esta es la suma de matrices \n',suma)

Esta es la suma de matrices 
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [14]:
# multiplicar matriz identidad x matriz del ejercicio anterior
multiplicacion = array6 * array4
print('Esta es la matriz multiplicada \n', multiplicacion)

Esta es la matriz multiplicada 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# división de las matrices
division = array6 / array4
print('Esta es la división de las matrices \n', division)

Esta es la división de las matrices 
 [[ 1. nan nan]
 [nan  1. nan]
 [nan nan  1.]]


/tmp/ipykernel_454/3563071699.py:2: RuntimeWarning: invalid value encountered in true_divide
  division = array6 / array4
