In [2]:
import numpy as np

In [3]:
# crear array bidimensional 5x3
array1 = np.random.rand(5,3)
print(array1)

[[0.62978462 0.59924965 0.20848005]
 [0.86970813 0.94262975 0.94262645]
 [0.65947394 0.78908841 0.68794864]
 [0.53360951 0.39900064 0.105938  ]
 [0.91442091 0.42159753 0.55719865]]


In [5]:
# valor de la primera fila y segunda columna
print('Esto es la primera fila y segunda columna: \n', array1[0,1])

Esto es la primera fila y segunda columna: 
 0.5992496452595529


In [6]:
# segunda fila y dos primeras columnas
print('Esto es la segunda fila y las dos primeras columnas: \n', array1[1,0:2])

Esto es la segunda fila y las dos primeras columnas: 
 [0.86970813 0.94262975]


In [7]:
# extraer filas pares y todas las columnas 
print('Esto son las filas pares (incluyendo 0) y todas las columnas: \n', array1[0:6:2,:])

Esto son las filas pares (incluyendo 0) y todas las columnas: 
 [[0.62978462 0.59924965 0.20848005]
 [0.65947394 0.78908841 0.68794864]
 [0.91442091 0.42159753 0.55719865]]


In [12]:
# valores > 0.5
print('Estos son los valores mayores que 0.5: \n', array1[array1 > 0.5])

Estos son los valores mayores que 0.5: 
 [0.62978462 0.59924965 0.86970813 0.94262975 0.94262645 0.65947394
 0.78908841 0.68794864 0.53360951 0.91442091 0.55719865]


In [14]:
# valores < 0.2 y > 0.5
print('Estos son los valores menores 0.2 y mayores que 0.5: \n', array1[(array1 < 0.2) | (array1 > 0.5)])

Estos son los valores menores 0.2 y mayores que 0.5: 
 [0.62978462 0.59924965 0.86970813 0.94262975 0.94262645 0.65947394
 0.78908841 0.68794864 0.53360951 0.105938   0.91442091 0.55719865]


In [17]:
# crear dos array de 3 dimensiones
array2 = np.random.rand(2,3,5)
array3 = np.random.rand(3,2,5)

In [18]:
# análisis exploratorio de los arrays creados
def analisis():
    lista_array = [array2, array3]
    for propiedad in lista_array:
        print(propiedad.shape)
        print(propiedad.size)
        print(propiedad.ndim)
        print(propiedad.dtype)

analisis()

(2, 3, 5)
30
3
float64
(3, 2, 5)
30
3
float64


In [19]:
#suma dos arrays
suma = array2 + array3 
#no se puede porque no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

In [23]:
array3

array([[[0.94886221, 0.64000471, 0.55309845, 0.7421356 , 0.12751405],
        [0.45870157, 0.32465653, 0.81138041, 0.85037737, 0.4420444 ]],

       [[0.12247644, 0.03857659, 0.49705476, 0.37752479, 0.58761515],
        [0.73993821, 0.61239881, 0.64654522, 0.41048085, 0.67392986]],

       [[0.97131743, 0.23431209, 0.59364752, 0.24958913, 0.29242516],
        [0.56385463, 0.32814455, 0.54852726, 0.02930059, 0.50950968]]])

In [24]:
# .reshape() y .transpose()
array3_transpose = array3.transpose(1,0,2)
array3_transpose

array([[[0.94886221, 0.64000471, 0.55309845, 0.7421356 , 0.12751405],
        [0.12247644, 0.03857659, 0.49705476, 0.37752479, 0.58761515],
        [0.97131743, 0.23431209, 0.59364752, 0.24958913, 0.29242516]],

       [[0.45870157, 0.32465653, 0.81138041, 0.85037737, 0.4420444 ],
        [0.73993821, 0.61239881, 0.64654522, 0.41048085, 0.67392986],
        [0.56385463, 0.32814455, 0.54852726, 0.02930059, 0.50950968]]])

In [26]:
array3_reshape = array3.reshape(2,3,5)
array3_reshape

array([[[0.94886221, 0.64000471, 0.55309845, 0.7421356 , 0.12751405],
        [0.45870157, 0.32465653, 0.81138041, 0.85037737, 0.4420444 ],
        [0.12247644, 0.03857659, 0.49705476, 0.37752479, 0.58761515]],

       [[0.73993821, 0.61239881, 0.64654522, 0.41048085, 0.67392986],
        [0.97131743, 0.23431209, 0.59364752, 0.24958913, 0.29242516],
        [0.56385463, 0.32814455, 0.54852726, 0.02930059, 0.50950968]]])

In [27]:
suma = array2 + array3_transpose
print(suma)

[[[0.99887126 0.69256712 0.72329445 0.89404077 0.76842161]
  [0.8600985  0.695135   0.80778301 0.92793651 1.35954286]
  [1.21833141 0.90860834 1.25417608 0.75656426 0.61961432]]

 [[1.22518671 1.2308147  1.36062421 1.38573383 0.8286388 ]
  [0.93559355 0.99934675 1.39259832 0.67800814 1.58073736]
  [1.14799583 0.80431222 1.42005094 0.89589441 1.35992768]]]


In [28]:
resta = array2 - array3_reshape
print(resta)

[[[-0.89885315 -0.5874423  -0.38290245 -0.59023044  0.51339351]
  [ 0.2789205   0.33190187 -0.50065216 -0.29996566  0.32988331]
  [ 0.12453755  0.63571966  0.1634738   0.12945034 -0.26042599]]

 [[ 0.02654693  0.29375937 -0.09730142  0.12487561 -0.28733547]
  [-0.77566208  0.15263585  0.15240558  0.01793817  0.61438234]
  [ 0.02028657  0.14802312  0.32299641  0.83729323  0.34090832]]]


In [29]:
multiplicacion = array2 * array3_transpose
print(multiplicacion)

[[[0.0474517  0.03364019 0.09413514 0.11273423 0.08172472]
  [0.09034132 0.02532779 0.15444895 0.20779407 0.45359642]
  [0.23992899 0.15799576 0.39212114 0.12653548 0.09567834]]

 [[0.35158793 0.29419017 0.44564566 0.45525502 0.17089189]
  [0.14477286 0.23696646 0.48235707 0.10981483 0.61112465]
  [0.32937072 0.15625182 0.4780545  0.02539171 0.4332962 ]]]


In [30]:
division = array2 / array3_reshape
print(division)

[[[ 0.05270423  0.08212816  0.30771375  0.20468653  5.02617221]
  [ 1.60806528  2.02231696  0.38296247  0.64725583  1.74626735]
  [ 2.01682859 17.47941385  1.32888489  1.34289229  0.55680859]]

 [[ 1.03587723  1.47968638  0.84950562  1.30421787  0.57364188]
  [ 0.20143296  1.65142117  1.25672739  1.07187078  3.10099004]
  [ 1.03597837  1.45109121  1.58884295 29.57598765  1.66909095]]]
