In [2]:
import numpy as np


In [3]:
# crear dos array con random_sample y que tengan los mismos valores
array_1 = np.random.rand(5)
array_2 = np.random.rand(5)


In [4]:
np.random.seed(12)
array_1_seed = np.random.rand(5)

In [5]:
array_1_seed

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496])

In [6]:
np.random.seed(12)
array_2_seed = np.random.rand(5)

In [7]:
array_2_seed

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496])

In [8]:
# crear array de 3 dimensiones, 2x3x5, sin decimales y entre 0-10; extrae sus valores únicos guardándolo en una variable
array_uniform = np.random.uniform(0,10, (2,3,5)).round(0)
array_uniform

array([[[ 9.,  9.,  0., 10.,  1.],
        [ 3.,  6.,  9.,  9.,  0.],
        [ 5.,  6.,  5.,  8.,  2.]],

       [[ 8.,  0.,  1.,  1.,  3.],
        [ 7.,  5.,  8.,  3.,  7.],
        [ 7.,  3.,  3., 10.,  6.]]])

In [9]:
valores_unicos = np.unique(array_uniform)
valores_unicos

array([ 0.,  1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
# crear array de 3 dimensiones, 2x3x5, con probabilidad 0.3 y nº pruebas = 10; guarda los valores únicos en una variable
array_binomial = np.random.binomial(10, 0.3, (2,3,5))
array_binomial

array([[[5, 4, 4, 3, 3],
        [3, 7, 2, 6, 3],
        [3, 3, 2, 3, 1]],

       [[1, 4, 3, 0, 2],
        [2, 1, 3, 3, 1],
        [3, 4, 1, 2, 3]]])

In [11]:
valores_unicos_2 = np.unique(array_binomial)
valores_unicos

array([ 0.,  1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
# elementos comunes entre valores únicos de array3 y array4
elementos_comunes = np.intersect1d(valores_unicos, valores_unicos_2)
print(elementos_comunes)

[0. 1. 2. 3. 5. 6. 7.]


In [13]:
# unión de elementos únicos de array3 y array4
union = np.union1d(valores_unicos, valores_unicos_2)
print(union)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [14]:
# ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
diferencia = np.setdiff1d(valores_unicos, valores_unicos_2)
print(diferencia)

[ 8.  9. 10.]


In [15]:
# crear dos arrays usando random.rand con 80 elementos, nº entre 1-100
array1 = np.random.randint(0,100, (80))
print(array1)

array2 = np.random.randint(0, 100, (80))
print(array2)

[57 54 56 97 68 25 44 22 69  9 59 27 28  2 68 48 44 52 68 35 71 54 30 49
 36 46 10 76 83 72 26 72 22 56 78 68 89 79  4 97 28 20 81 26  4 91 19 88
 43 93 64 97 68 95 38 37 20 66 90 74 96 95 34 74 50 80 17 20 42 39 30 17
 70 81 67 15  0 33 44 45]
[20 26 40 72 88  8 15 76 62 47 19 14 30 43 15 14  5 65 15 22 82 19 28 17
 89 93 30 19 66 98 47 59  8 41 37 57  1 55 36 61 13 80 46 93 81 36 10 55
 66 15 62 94 36 96 88 51  5 98 63 26  4 30 23 93 53 32 27 66 76 68 63 22
 29 50 87 50 33 69 83 46]


In [16]:
# Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2
array1 = np.unique(array1)
print(array1)

array2 = np.unique(array2)
print(array2)

[ 0  2  4  9 10 15 17 19 20 22 25 26 27 28 30 33 34 35 36 37 38 39 42 43
 44 45 46 48 49 50 52 54 56 57 59 64 66 67 68 69 70 71 72 74 76 78 79 80
 81 83 88 89 90 91 93 95 96 97]
[ 1  4  5  8 10 13 14 15 17 19 20 22 23 26 27 28 29 30 32 33 36 37 40 41
 43 46 47 50 51 53 55 57 59 61 62 63 65 66 68 69 72 76 80 81 82 83 87 88
 89 93 94 96 98]


In [17]:
# Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3
array3 = np.setdiff1d(array1, array2)
print(array3)

[ 0  2  9 25 34 35 38 39 42 44 45 48 49 52 54 56 64 67 70 71 74 78 79 90
 91 95 97]


In [18]:
# Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4
array4 = np.setdiff1d(array2, array1)
print(array4)

[ 1  5  8 13 14 23 29 32 40 41 47 51 53 55 61 62 63 65 82 87 94 98]


In [19]:
# Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5
array5 = np.intersect1d(array1, array2)
print(array5)

[ 4 10 15 17 19 20 22 26 27 28 30 33 36 37 43 46 50 57 59 66 68 69 72 76
 80 81 83 88 89 93 96]


In [20]:
# ¿Cuál es la relación que existe entre todos estos arrays?
forma_1 = len(array1)
print(forma_1)

forma_2 = len(array2)
print(forma_2)

forma_3 = len(array3)
print(forma_3)

forma_4 = len(array4)
print(forma_4)

forma_5 = len(array5)
print(forma_5)

print(len(array1) + len(array4) - len(array5)  == len(array2) + len(array3) - len(array5))

58
53
27
22
31
True
